[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200

[[redirects]]
  from = "/api/checkout-session-access"
  to = "/.netlify/functions/checkout-session-access"
  status = 200
